// One set of live subscriptions serves the rail, discovery, and conversations.
export const dmKey=(self,other)=>'dm_'+[self,other].sort().join('_');
export function liveNames(presence){return new Set(Object.values(presence||{}).filter(p=>p?.online===true&&p.username).map(p=>p.username));}
export function activeStreak(value,now=new Date()){
 const today=now.toDateString(),yesterday=new Date(now.getTime()-86400000).toDateString();
 return value&&(value.lastDate===today||value.lastDate===yesterday)?Math.max(0,Number(value.count)||0):0;
}
export function selectPeople({users,friends,blocked,online,self,query='',onlyOnline=false}){
 const q=query.trim().toLowerCase();return Object.keys(users).filter(name=>name!==self&&!blocked[name]&&(!onlyOnline||online.has(name))&&(!q||(name+' '+(users[name]?.displayName||'')).toLowerCase().includes(q))).sort((a,b)=>Number(online.has(b))-Number(online.has(a))||Number(!!friends[b])-Number(!!friends[a])||a.localeCompare(b)).slice(0,40);
}
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn,cls='ns-action')=>{const n=el('button',cls,text);n.type='button';n.onclick=fn;return n;};
const photo=value=>{try{const u=new URL(value,location.href);return value&&(['https:','http:'].includes(u.protocol)||/^data:image\/(png|jpeg|webp|gif);base64,/i.test(value))?u.href:'';}catch{return '';}};
export function mountChatSidebar({self,subscribe,getView,getChannel,openDM,sendRequest,acceptRequest,ignoreRequest,openGroup,manageGroup,leaveGroup,createGroup,profile,nickname,mute,block,removeFriend}){
 let users={},friends={},presence={},blocked={},nicknames={},unread={},requests={},groups={},query='',filter='all',queued=false,disposed=false,onlineNames=new Set();
 const stops=[],streaks={},streakStops=new Map(),pending=new Set(),railCards=new Map(),friendCards=new Map();
 const sidebar=document.querySelector('.sidebar'),rail=el('nav','ns-friend-rail');rail.setAttribute('aria-label','Friends');document.querySelector('.server-list').append(rail);
 const tip=el('div','ns-tooltip');tip.hidden=true;document.body.append(tip);
 const pane=el('section','ns-directory');pane.hidden=true;sidebar.append(pane);
 const heading=el('div','ns-heading');heading.append(el('small','','YOUR PEOPLE'),el('h2','','Messages'));const add=button('+',()=>{search.focus();search.select();},'ns-add');add.title='Find people to add';add.setAttribute('aria-label',add.title);heading.append(add);
 const search=el('input','ns-search');search.type='search';search.placeholder='Search people or add friends';search.setAttribute('aria-label','Search people or add friends');search.oninput=()=>{query=search.value;schedule();};
 const tabs=el('div','ns-filters'),all=button('Friends',()=>{filter='all';schedule();}),onlineButton=button('Online',()=>{filter='online';schedule();});tabs.append(all,onlineButton);
 const message=el('p','ns-feedback');message.setAttribute('role','status');
 const requestList=el('div','ns-requests'),friendList=el('div','ns-friends'),discovery=el('div','ns-discovery'),groupList=el('div','ns-groups');
 const friendActions=el('div','ns-friend-actions');friendActions.hidden=true;
 pane.append(heading,search,tabs,message,requestList,friendList,friendActions,discovery,groupList,button('+ Create group',createGroup,'ns-create'));
 const modal=document.getElementById('userProfileModal'),modalStreak=el('span','ns-modal-streak');modalStreak.hidden=true;document.querySelector('.discord-username-section')?.append(modalStreak);const modalObserver=modal?new MutationObserver(schedule):null;modalObserver?.observe(modal,{attributes:true,attributeFilter:['data-account']});
 const profileStreak=el('span','ns-profile-streak');profileStreak.hidden=true;document.querySelector('.user-profile-info')?.append(profileStreak);
 function label(name){return nicknames[name]||users[name]?.displayName||name;}
 function avatar(name){const a=el('span','ns-avatar'),initial=el('span','',label(name).slice(0,1).toUpperCase()),img=el('img'),dot=el('i','ns-presence');img.alt='';img.hidden=true;img.onerror=()=>{img.hidden=true;};a.append(initial,img,dot);return a;}
 function updateAvatar(a,name){a.children[0].textContent=label(name).slice(0,1).toUpperCase();const src=photo(users[name]?.profilePic||friends[name]?.profilePic);if(a.dataset.photo!==src){a.dataset.photo=src;a.children[1].hidden=!src;if(src)a.children[1].src=src;else a.children[1].removeAttribute('src');}a.classList.toggle('online',onlineNames.has(name));}
 function showTip(node,name){tip.textContent=label(name);tip.hidden=false;const r=node.getBoundingClientRect();tip.style.top=Math.max(8,Math.min(innerHeight-45,r.top+5))+'px';tip.style.left=(r.right+10)+'px';}
 function card(name,compact){const n=button('',()=>openDM(name),compact?'ns-rail-person':'ns-person');const a=avatar(name),text=el('span','ns-person-copy'),title=el('strong'),sub=el('small'),streak=el('span','ns-streak'),badge=el('span','ns-unread');text.append(title,sub);n.append(a,text,streak,badge);n.parts={a,title,sub,streak,badge};if(compact){n.onmouseenter=n.onfocus=()=>showTip(n,name);n.onmouseleave=n.onblur=()=>tip.hidden=true;}return n;}
 function updateCard(n,name,online){const {a,title,sub,streak,badge}=n.parts;updateAvatar(a,name);title.textContent=label(name);sub.textContent=online.has(name)?'Online now':'Offline';const count=activeStreak(streaks[dmKey(self,name)]);streak.textContent='🔥 '+count;streak.hidden=!count;streak.title=count+' day conversation streak';const num=Number(unread[dmKey(self,name)])||0;badge.textContent=num>99?'99+':String(num);badge.hidden=!num;n.classList.toggle('active',getChannel()===dmKey(self,name));n.setAttribute('aria-label',label(name)+(online.has(name)?', online':', offline')+(count?', '+count+' day streak':'')+(num?', '+num+' unread':''));n.setAttribute('aria-current',String(getChannel()===dmKey(self,name)));}
 function reconcile(container,map,names,compact,online){for(const [name,n]of map)if(!names.includes(name)){n.remove();map.delete(name);}let previous=null;for(const name of names){let n=map.get(name);if(!n){n=card(name,compact);map.set(name,n);}updateCard(n,name,online);const expected=previous?previous.nextSibling:container.firstChild;if(expected!==n)container.insertBefore(n,expected);previous=n;}}
 function schedule(){if(!queued&&!disposed){queued=true;requestAnimationFrame(render);}}
 function observe(path,fn){return subscribe(path,value=>{fn(value||{});schedule();},()=>{message.textContent='Could not update people. Check your connection.';});}
 function trackStreaks(){const wanted=new Set([...Object.keys(friends).filter(n=>!blocked[n]).map(n=>dmKey(self,n)),...Object.keys(groups).filter(id=>groups[id]?.members?.[self])]);for(const [key,stop]of streakStops)if(!wanted.has(key)){stop();streakStops.delete(key);delete streaks[key];}for(const key of wanted)if(!streakStops.has(key))streakStops.set(key,observe('streaks/'+key,v=>streaks[key]=v));}
 let requestsSignature='',discoverySignature='',groupsSignature='',actionSignature='';
 function render(){queued=false;if(disposed)return;const online=onlineNames=liveNames(presence),isDM=getView()==='dms';document.body.classList.toggle('nova-dm-view',isDM);pane.hidden=!isDM;document.getElementById('sidebarHeader').textContent=isDM?'Direct messages':'Nova Chat';
 const names=Object.keys(friends).filter(n=>!blocked[n]).sort((a,b)=>Number(online.has(b))-Number(online.has(a))||label(a).localeCompare(label(b)));
 reconcile(rail,railCards,names,true,online);all.setAttribute('aria-pressed',String(filter==='all'));onlineButton.setAttribute('aria-pressed',String(filter==='online'));onlineButton.textContent='Online · '+names.filter(n=>online.has(n)).length;
 const visible=names.filter(n=>(filter!=='online'||online.has(n))&&(!query||(n+' '+label(n)).toLowerCase().includes(query.toLowerCase())));reconcile(friendList,friendCards,visible,false,online);
 message.textContent=visible.length?'':query?'No matching friends. Find someone below.':filter==='online'?'Your friends are offline right now.':'Your people will appear here. Search to add a friend.';
 const modalCount=activeStreak(streaks[dmKey(self,modal?.dataset.account||'')]);modalStreak.hidden=!modalCount;modalStreak.textContent='🔥 '+modalCount+' day streak together';
 const currentStreak=activeStreak(streaks[getChannel()]);profileStreak.hidden=!currentStreak;profileStreak.textContent='🔥 '+currentStreak+' day chat streak';profileStreak.title='Streak for this conversation';
 if(!isDM)return;
 const selected=Object.keys(friends).find(n=>getChannel()===dmKey(self,n));const actionKey=JSON.stringify([selected,!!blocked[selected]]);if(actionKey!==actionSignature){actionSignature=actionKey;friendActions.replaceChildren();friendActions.hidden=!selected;if(selected)for(const [title,action]of [['Profile',profile],['Nickname',nickname],['Mute / unmute',mute],[blocked[selected]?'Unblock':'Block',block],['Remove friend',removeFriend]])friendActions.append(button(title,()=>action(selected)));}
 const requestEntries=Object.entries(requests).filter(([,r])=>r?.from&&!blocked[r.from]);const sig=JSON.stringify(requestEntries);if(sig!==requestsSignature){requestsSignature=sig;requestList.replaceChildren();if(requestEntries.length)requestList.append(el('h3','','FRIEND REQUESTS'));for(const [id,r]of requestEntries){const row=el('div','ns-request');row.append(el('strong','',label(r.from)));for(const [title,action]of [['Accept',()=>acceptRequest(id,r.from,r.fromPic||'')],['Ignore',()=>ignoreRequest(id,r.from)]])row.append(button(title,action));requestList.append(row);}}
 const found=selectPeople({users,friends,blocked,online,self,query,onlyOnline:!query}).filter(n=>!friends[n]);const ds=JSON.stringify(found.map(n=>[n,label(n),users[n]?.profilePic,online.has(n),pending.has(n)]));if(ds!==discoverySignature){discoverySignature=ds;discovery.replaceChildren();discovery.append(el('h3','',query?'FIND PEOPLE':'ONLINE ON NOVA'));if(!found.length)discovery.append(el('p','ns-empty',query?'No users match that search.':'Nobody new online right now.'));for(const name of found){const row=el('div','ns-discovery-person'),a=avatar(name),copy=el('span','ns-person-copy');updateAvatar(a,name);copy.append(el('strong','',label(name)),el('small','',online.has(name)?'Online now':'@'+name));const add=button(pending.has(name)?'Sent':'Add',async()=>{add.disabled=true;try{await sendRequest(name);pending.add(name);schedule();}catch{add.disabled=false;message.textContent='Could not send the request. Try again.';}});add.disabled=pending.has(name);add.setAttribute('aria-label','Add '+name);row.append(a,copy,add);discovery.append(row);}}
 const own=Object.entries(groups).filter(([,g])=>g?.members?.[self]);const gs=JSON.stringify(own.map(([id,g])=>[id,g.name,g.creator,unread[id],activeStreak(streaks[id]),getChannel()===id]));if(gs!==groupsSignature){groupsSignature=gs;groupList.replaceChildren();if(own.length)groupList.append(el('h3','','GROUPS'));for(const [id,g]of own){const row=el('div','ns-group');row.append(button(g.name||'Group',()=>openGroup(id,g.name),'ns-group-name'),button(g.creator===self?'⚙':'↗',()=>g.creator===self?manageGroup(id):leaveGroup(id)));row.firstChild.classList.toggle('active',getChannel()===id);row.lastChild.setAttribute('aria-label',g.creator===self?'Group settings':'Leave group');const count=activeStreak(streaks[id]),num=Number(unread[id])||0;if(count)row.append(el('span','ns-streak','🔥 '+count));if(num)row.append(el('span','ns-unread',num>99?'99+':String(num)));groupList.append(row);}}
 }
 friendList.oncontextmenu=e=>{const n=e.target.closest('.ns-person');if(!n)return;e.preventDefault();const name=[...friendCards].find(([,v])=>v===n)?.[0];if(name)profile(name);};
 // Existing profile actions remain available through a small explicit menu.
 friendList.addEventListener('dblclick',e=>{const n=e.target.closest('.ns-person'),name=[...friendCards].find(([,v])=>v===n)?.[0];if(name)profile(name);});
 stops.push(observe('friends/'+self,v=>{friends=Object.fromEntries(Object.entries(v).map(([k,f])=>[f.username||k,f]));trackStreaks();}),observe('presence',v=>presence=v),observe('blocked/'+self,v=>{blocked=v;trackStreaks();}),observe('nicknames/'+self,v=>nicknames=v),observe('unreadMessages/'+self,v=>unread=v),observe('friendRequests/'+self,v=>requests=v),observe('groups',v=>{groups=v;trackStreaks();}));
 function destroy(){disposed=true;modalObserver?.disconnect();stops.forEach(stop=>stop());streakStops.forEach(stop=>stop());rail.remove();pane.remove();tip.remove();}
 window.addEventListener('pagehide',destroy,{once:true});schedule();return {refresh:schedule,setUsers(value){users=value||{};schedule();},destroy};
}
