(()=>{'use strict';
if(parent===window){document.body.classList.add('standalone-music');try{const source=localStorage.getItem('nova_wallpaper_upload')||localStorage.getItem('nova_wallpaper');if(source){const url=new URL(source,location.href);if(['https:','http:','data:','blob:'].includes(url.protocol)){const backdrop=document.createElement('div');backdrop.className='music-wallpaper';if(localStorage.getItem('nova_wallpaper_is_video')==='true'){const video=document.createElement('video');video.src=url.href;video.muted=true;video.loop=true;video.autoplay=true;video.playsInline=true;backdrop.append(video);}else{backdrop.style.backgroundImage='url('+JSON.stringify(url.href)+')';}document.body.prepend(backdrop);}}}catch{}}
const $=id=>document.getElementById(id),audio=new Audio();audio.volume=.7;let saved={favorites:[],playlists:[]};try{saved=JSON.parse(localStorage.getItem('nova-music-library'))||saved}catch{}if(!Array.isArray(saved.favorites)||!Array.isArray(saved.playlists))saved={favorites:[],playlists:[]};let results=[],view='discover',active=null,request;
const node=(tag,text)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;return el};const persist=()=>{try{localStorage.setItem('nova-music-library',JSON.stringify(saved))}catch{$('status').textContent='Your browser could not save the library.'}};const safe=url=>{try{return new URL(url).protocol==='https:'?url:''}catch{return ''}};
function sidebar(){$('lists').replaceChildren();saved.playlists.forEach(p=>{const b=node('button','♫ '+p.name);b.onclick=()=>{view=p.id;render()};$('lists').append(b)})}
function render(){if($("home-rows"))$("home-rows").hidden=true;const list=view==='discover'?results:view==='favorites'?saved.favorites:saved.playlists.find(p=>p.id===view)?.songs||[];$('title').textContent=view==='discover'?'Discover':view==='favorites'?'Your favorites':saved.playlists.find(p=>p.id===view)?.name||'Playlist';$('tracks').replaceChildren();$('status').textContent=list.length?list.length+' previews':view==='discover'?'Search for an artist or song to begin.':'Your collection starts here. Add songs from search.';list.forEach(s=>{const card=node('article');card.className='track';const cover=node('button');cover.className='cover';cover.setAttribute('aria-label','Play preview of '+s.name);const img=node('img');img.src=safe(s.art);img.alt='';img.loading='lazy';cover.append(img,node('span','▶'));cover.onclick=()=>play(s);const actions=node('div');actions.className='actions';const heart=node('button','♥');heart.className='heart';heart.setAttribute('aria-label','Favorite '+s.name);heart.setAttribute('aria-pressed',saved.favorites.some(f=>f.id===s.id));heart.onclick=()=>{const i=saved.favorites.findIndex(f=>f.id===s.id);if(i<0)saved.favorites.push(s);else saved.favorites.splice(i,1);persist();render()};const select=node('select');select.setAttribute('aria-label','Add '+s.name+' to playlist');const option=node('option','＋ Playlist');option.value='';select.append(option);saved.playlists.forEach(p=>{const o=node('option',p.name);o.value=p.id;select.append(o)});select.onchange=()=>{const p=saved.playlists.find(p=>p.id===select.value);if(p&&!p.songs.some(f=>f.id===s.id)){p.songs.push(s);persist();$('status').textContent='Added to '+p.name}select.value=''};actions.append(heart,select);card.append(cover,node('h3',s.name),node('p',s.artist),actions);$('tracks').append(card)})}
async function play(s){active=s;$('song').textContent=s.name;$('artist').textContent=s.artist+' · Preview';$('art').src=safe(s.art);$('art').hidden=false;$('play').disabled=false;audio.src=safe(s.url);try{await audio.play()}catch{$('status').textContent='This preview could not play. Try another song.'}}
audio.onplay=()=>{$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','Pause')};audio.onpause=audio.onended=()=>{$('play').textContent='▶';$('play').setAttribute('aria-label','Play')};audio.onerror=()=>{$('status').textContent='Preview unavailable. Try another song.'};audio.ontimeupdate=()=>{$('seek').disabled=!Number.isFinite(audio.duration);$('seek').value=audio.duration?audio.currentTime/audio.duration*100:0;$('time').textContent=Math.floor(audio.currentTime/60)+':'+String(Math.floor(audio.currentTime%60)).padStart(2,'0')};$('seek').oninput=e=>{if(Number.isFinite(audio.duration))audio.currentTime=e.target.value/100*audio.duration};$('volume').oninput=e=>audio.volume=Number(e.target.value);$('play').onclick=()=>{if(active)audio.paused?audio.play().catch(()=>{$('status').textContent='Could not resume preview.'}):audio.pause()};
$('search').onsubmit=async e=>{e.preventDefault();const q=$('query').value.trim();if(!q)return;if(location.protocol==='file:'){$('status').textContent='Open Nova from its website address to search music. Search cannot run from a downloaded HTML file.';return;}request?.abort();const controller=request=new AbortController();view='discover';$('status').textContent='Finding your music…';const timeout=setTimeout(()=>controller.abort(),15000);try{const r=await fetch('/api/music-search?term='+encodeURIComponent(q),{signal:controller.signal});if(!r.ok)throw Error();const data=await r.json();if(request!==controller)return;results=(data.results||[]).filter(s=>safe(s.previewUrl)).map(s=>({id:s.trackId,name:s.trackName,artist:s.artistName,art:s.artworkUrl100,url:s.previewUrl}));if(view==='discover')render()}catch{if(request===controller)$('status').textContent='Music search could not connect. Please try again.'}finally{clearTimeout(timeout)}};
$('favorites').onclick=()=>{view='favorites';render()};$('discover').onclick=()=>{view='discover';render()};$('new-list').onclick=()=>$('playlist-dialog').showModal();$('playlist-dialog').addEventListener('close',()=>{if($('playlist-dialog').returnValue!=='create')return;const name=$('playlist-name').value.trim();if(!name)return;saved.playlists.push({id:crypto.randomUUID(),name,songs:[]});$('playlist-name').value='';persist();sidebar();render()});$('close').onclick=()=>{publish();if(parent!==window)parent.postMessage({novaAction:'closeMusic'},location.origin);else location.href='home.html'};sidebar();render();
function publish(){if(parent!==window)parent.postMessage({novaAction:'musicState',song:active,playing:!audio.paused,time:audio.currentTime,duration:Number.isFinite(audio.duration)?audio.duration:0},location.origin);}
['play','pause','ended','timeupdate','loadedmetadata'].forEach(name=>audio.addEventListener(name,publish));
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.novaAction==='musicToggle')$('play').click();});
$('moods').addEventListener('click',e=>{const b=e.target.closest('[data-query]');if(!b)return;$('moods').querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===b));$('query').value=b.dataset.query;$('search').requestSubmit();});

let homeVersion=0;const homeCache=new Map();
function browse(){homeVersion++;$('home-rows').hidden=true;$('search').hidden=false;$('moods').hidden=false;$('query').focus();}
$('search-nav').onclick=browse;
$('search').addEventListener('submit',()=>{homeVersion++;$('home-rows').hidden=true;});
$('favorites').addEventListener('click',()=>{homeVersion++;});
$('lists').addEventListener('click',()=>{homeVersion++;});
async function home(){const version=++homeVersion;view='discover';$('search').hidden=true;$('moods').hidden=true;$('tracks').replaceChildren();$('title').textContent='Made for your day';$('status').textContent='Loading your music shelves…';$('home-rows').replaceChildren();$('home-rows').hidden=false;
const shelves=[['Artist spotlight','Daft Punk'],['Indie afternoons','indie folk'],['After hours','electronic chill']];
await Promise.all(shelves.map(async ([label,q],i)=>{const row=node('section');row.className='music-shelf';row.style.order=i;row.append(node('h2',label));const grid=node('div');grid.className='shelf-grid';row.append(grid);$('home-rows').append(row);try{let songs=homeCache.get(q);if(!songs){const r=await fetch('/api/music-search?term='+encodeURIComponent(q),{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const d=await r.json();songs=d.results.filter(s=>safe(s.previewUrl)).slice(0,6).map(s=>({id:s.trackId,name:s.trackName,artist:s.artistName,art:s.artworkUrl100,url:s.previewUrl}));homeCache.set(q,songs);}if(version!==homeVersion)return;const old=results;results=songs;render();grid.append(...$('tracks').children);results=old;$('home-rows').hidden=false;}catch{grid.append(node('p','This shelf is unavailable. Try Search.'));}}));if(version===homeVersion){results=[...homeCache.values()].flat();$('title').textContent='Discover';$('status').textContent='Song previews · Explore something new';}}
$('discover').onclick=home;
const hour=new Date().getHours();$('greeting').textContent=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';
function skip(step){const list=view==='favorites'?saved.favorites:view==='discover'?results:saved.playlists.find(p=>p.id===view)?.songs||[];if(!list.length)return;const index=list.findIndex(s=>s.id===active?.id);play(list[(index+step+list.length)%list.length]);}
$('previous').onclick=()=>{if(audio.currentTime>3)audio.currentTime=0;else skip(-1)};$('next').onclick=()=>skip(1);
if(location.protocol!=='file:')home();
})();
