import {mountVoiceAccount,voiceIdentity} from './voice-account.js';
import {createVoiceView,paintMembers,paintSpeaking,icon} from './voice-ui.js';
export function mountVoice(){
 const main=document.querySelector('.chat-main'),general=createVoiceView(),privateView=createVoiceView(true);
 main.append(general);mountVoiceAccount(general);
 const dialog=document.createElement('dialog');dialog.className='nova-call-dialog';const minimize=document.createElement('button');minimize.className='voice-minimize';minimize.textContent='Back to chat';minimize.onclick=()=>dialog.close();dialog.append(minimize,privateView);document.body.append(dialog);
 const tab=document.createElement('button');tab.className='channel nova-voice-tab';tab.innerHTML=icon('wave')+'<span>Voice Chat</span><span class="voice-tab-count">0 / 10</span>';document.getElementById('channelsList').before(tab);
 function openTab(){main.classList.add('nova-voice-view');general.hidden=false;tab.classList.add('active');tab.setAttribute('aria-pressed','true');refreshLobby();}
 function closeTab(){main.classList.remove('nova-voice-view');general.hidden=true;tab.classList.remove('active');tab.setAttribute('aria-pressed','false');}
 tab.onclick=openTab;for(const key of ['switchChannel','switchView']){const original=window[key];if(original)window[key]=function(...args){closeTab();return original.apply(this,args);};}
 const dm=document.createElement('button');dm.className='header-btn nova-dm-call';dm.title='Call this friend privately';dm.innerHTML=icon('phone')+'<span>Call friend</span>';document.querySelector('.header-actions')?.prepend(dm);
 const resume=document.createElement('button');resume.className='header-btn nova-dm-call';resume.hidden=true;resume.innerHTML=icon('phone')+'<span>Open call</span>';resume.onclick=()=>{if(call?.room==='server-general')openTab();else showPrivate();};document.querySelector('.header-actions')?.prepend(resume);
 let call=null,busy=false,muted=false,deaf=false,generation=0,pendingView=null,lobbyBusy=false,checking=false,audioContext=null,meterTimer=null;const peers=new Map(),meters=new Map();
 const status=(view,text)=>{view.querySelector('[role=status]').textContent=text;};
 async function request(body){const user=await voiceIdentity();const r=await fetch('/api/voice',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await user.getIdToken()},body:JSON.stringify(body),signal:AbortSignal.timeout(12000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Voice connection failed.');return data;}
 function showPrivate(){if(!dialog.open)dialog.showModal();}
 function controls(){for(const view of [general,privateView]){const active=call?.view===view,waiting=busy&&pendingView===view;view.querySelector('[data-mute]').disabled=!active;view.querySelector('[data-deafen]').disabled=!active;view.querySelector('[data-leave]').disabled=!active&&!waiting;for(const [key,on,yes,no] of [['mute',muted,'Unmute','Mute'],['deafen',deaf,'Undeafen','Deafen']]){const button=view.querySelector('[data-'+key+']');button.querySelector('span').textContent=active&&on?yes:no;button.classList.toggle('is-selected',active&&on);button.setAttribute('aria-pressed',String(active&&on));}}
  general.querySelector('[data-join-general]').disabled=busy||!!call;resume.hidden=!call;
 }
 function removeMeter(id){const meter=meters.get(id);if(meter){meter.source.disconnect();meter.analyser.disconnect();meters.delete(id);}}
 function watchAudio(id,stream){removeMeter(id);if(!audioContext||!stream)return;try{const source=audioContext.createMediaStreamSource(stream),analyser=audioContext.createAnalyser();analyser.fftSize=512;source.connect(analyser);meters.set(id,{source,analyser,data:new Float32Array(analyser.fftSize),last:0});}catch{}}
 function startMeters(){const Context=window.AudioContext||window.webkitAudioContext;if(!Context)return;try{audioContext=new Context();audioContext.resume().catch(()=>{});meterTimer=setInterval(()=>{if(!call)return;for(const [id,m] of meters){m.analyser.getFloatTimeDomainData(m.data);const rms=Math.sqrt(m.data.reduce((sum,n)=>sum+n*n,0)/m.data.length);if(rms>.025&&!(id===call.session&&muted))m.last=Date.now();paintSpeaking(call.view,id,Date.now()-m.last<250&&!(id===call.session&&muted));}},100);}catch{}}
 function removePeer(id){const p=peers.get(id);if(!p)return;removeMeter(id);p.pc.close();p.audio.srcObject=null;p.audio.remove();peers.delete(id);}
 function leave(){generation++;const old=call;call=null;for(const id of [...peers.keys()])removePeer(id);for(const id of [...meters.keys()])removeMeter(id);clearInterval(meterTimer);meterTimer=null;if(audioContext){audioContext.close().catch(()=>{});audioContext=null;}old?.stream.getTracks().forEach(t=>t.stop());if(old){request({action:'leave',room:old.room,session:old.session}).catch(()=>{});old.view.querySelector('[data-state]').textContent='Call ended';status(old.view,'You left the call.');paintMembers(old.view,{},'');}muted=deaf=false;controls();refreshLobby();}
 async function join(room,target=null,friend=''){
  const view=room==='server-general'?general:privateView;
  if(call||busy){status(view,'Leave your current call before starting another.');return;}
  if(view===general)openTab();else{showPrivate();privateView.querySelector('h1').textContent=friend?'Call with '+friend:'Private call';}
  busy=true;pendingView=view;const version=++generation;controls();status(view,'Connecting your microphone…');view.querySelector('[data-state]').textContent='Connecting';startMeters();let stream,joined;
  try{
   if(!navigator.mediaDevices?.getUserMedia)throw Error('Voice requires microphone support and HTTPS.');
   await voiceIdentity();await request({action:'invites'});if(version!==generation)return;
   stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});
   if(version!==generation){stream.getTracks().forEach(t=>t.stop());return;}
   if(target)room=(await request({action:'call',target})).room;
   const session=crypto.randomUUID(),config=await request({action:'join',room,session});joined={room,session};
   if(version!==generation){stream.getTracks().forEach(t=>t.stop());await request({action:'leave',...joined});return;}
   call={room,session,stream,view,iceServers:config.iceServers,ack:[],seen:new Set()};watchAudio(session,stream);view.querySelector('[data-direct]').replaceChildren();view.querySelector('[data-state]').textContent=target?'Ringing…':view===general?'In General Voice':'Private call';status(view,target?'Waiting for your friend to answer…':'You’re in. Say hello.');poll(version);
  }catch(e){stream?.getTracks().forEach(t=>t.stop());if(joined)request({action:'leave',...joined}).catch(()=>{});if(version===generation){leave();status(view,e.name==='NotAllowedError'?'Allow microphone access to join the call.':e.message);}}
  finally{busy=false;pendingView=null;controls();}
 }
 async function signal(id,data){if(call)await request({action:'signal',room:call.room,session:call.session,to:id,signal:data});}
 function peer(id){if(peers.has(id))return peers.get(id);const current=call,pc=new RTCPeerConnection({iceServers:current.iceServers}),audio=document.createElement('audio');audio.autoplay=true;audio.muted=deaf;document.body.append(audio);const p={pc,audio,candidates:[]};peers.set(id,p);current.stream.getTracks().forEach(t=>pc.addTrack(t,current.stream));pc.onicecandidate=e=>{if(e.candidate&&call===current)signal(id,{type:'candidate',candidate:e.candidate.toJSON()}).catch(()=>{});};pc.ontrack=e=>{const stream=e.streams[0]||new MediaStream([e.track]);audio.srcObject=stream;watchAudio(id,stream);audio.play().catch(()=>{current.view.querySelector('[data-audio]').hidden=false;});};pc.onconnectionstatechange=()=>{if(call!==current)return;if(pc.connectionState==='connected'){status(current.view,'Connected · Your conversation is live');current.view.querySelector('[data-state]').textContent='Connected';}if(pc.connectionState==='failed')status(current.view,'Audio could not connect. Rejoin; this network may need a TURN relay.');};return p;}
 async function poll(version){if(!call||generation!==version)return;try{const current=call,data=await request({action:'poll',room:current.room,session:current.session,ack:current.ack,muted,deafened:deaf});if(call!==current)return;current.ack=[];paintMembers(current.view,data.members,current.session);const ids=Object.keys(data.members);if(current.room==='server-general')countRoom(ids.length);
   for(const id of [...peers.keys()])if(!ids.includes(id))removePeer(id);
   for(const id of ids){if(id===current.session)continue;const fresh=!peers.has(id),p=peer(id);if(fresh&&current.session<id){await p.pc.setLocalDescription(await p.pc.createOffer());await signal(id,{type:'offer',sdp:p.pc.localDescription.sdp});}}
   for(const item of data.signals){if(call!==current)return;current.ack.push(item.id);if(current.seen.has(item.id)||!ids.includes(item.from))continue;const p=peer(item.from),s=item.signal;if(s.type==='candidate'){if(p.pc.remoteDescription)await p.pc.addIceCandidate(s.candidate);else p.candidates.push(s.candidate);}else{await p.pc.setRemoteDescription({type:s.type,sdp:s.sdp});for(const candidate of p.candidates)await p.pc.addIceCandidate(candidate);p.candidates=[];if(s.type==='offer'){await p.pc.setLocalDescription(await p.pc.createAnswer());await signal(item.from,{type:'answer',sdp:p.pc.localDescription.sdp});}}current.seen.add(item.id);}
  }catch(e){if(generation===version){const view=call?.view;leave();if(view)status(view,e.message);}return;}setTimeout(()=>poll(version),1500);
 }
 function countRoom(count){tab.querySelector('.voice-tab-count').textContent=count+' / 10';general.querySelector('[data-count]').textContent=String(count);}
 async function refreshLobby(){if(lobbyBusy||call?.room==='server-general')return;lobbyBusy=true;try{const data=await request({action:'lobby'});if(call?.room!=='server-general'){paintMembers(general,data.members,'');countRoom(Object.keys(data.members).length);}}catch(e){if(!general.hidden)status(general,e.message);}finally{lobbyBusy=false;}}
 for(const view of [general,privateView]){
  view.querySelector('[data-leave]').onclick=leave;
  view.querySelector('[data-mute]').onclick=()=>{if(call?.view!==view)return;muted=!muted;call.stream.getAudioTracks().forEach(t=>t.enabled=!muted);controls();paintSpeaking(view,call.session,false);};
  view.querySelector('[data-deafen]').onclick=()=>{if(call?.view!==view)return;deaf=!deaf;for(const p of peers.values())p.audio.muted=deaf;controls();};
  view.querySelector('[data-audio]').onclick=()=>{audioContext?.resume().catch(()=>{});for(const p of peers.values())p.audio.play().catch(()=>{});view.querySelector('[data-audio]').hidden=true;};
 }
 const heading=document.getElementById('channelName');function dmTarget(){try{return decodeURIComponent(heading.dataset.dmAccount||'');}catch{return '';}}function paint(){dm.hidden=!dmTarget();}new MutationObserver(paint).observe(heading,{attributes:true,attributeFilter:['data-dm-account']});paint();
 dm.onclick=async()=>{if(call){resume.onclick();return;}showPrivate();const name=dmTarget();privateView.querySelector('h1').textContent='Call '+name;const area=privateView.querySelector('[data-direct]');area.replaceChildren();paintMembers(privateView,{},'');status(privateView,'Finding your friend…');try{const data=await request({action:'peers',target:name});status(privateView,data.peers.length?'Choose your friend’s device. Their ID is shown so you can confirm it’s them.':'Your friend is offline. Ask them to open Nova Chat.');for(const item of data.peers){const b=document.createElement('button');b.className='voice-peer-choice';const label=document.createElement('strong'),id=document.createElement('small');label.textContent='Call '+item.name;id.textContent=item.id;b.append(label,id);b.onclick=()=>join(null,item.id,item.name);area.append(b);}}catch(e){status(privateView,e.message);}};
 window.novaJoinServerVoice=()=>join('server-general');general.querySelector('[data-join-general]').onclick=window.novaJoinServerVoice;
 const incomingSeen=new Set();const timer=setInterval(async()=>{if(checking)return;try{const hidden=window.frameElement?.closest('.panel-overlay')&&!window.frameElement.closest('.panel-overlay').classList.contains('open');if(hidden){if(call||busy)leave();return;}if((call||busy)&&window.NovaCommunity&&!window.NovaCommunity.canSend())leave();checking=true;const data=await request({action:'invites'});const incoming=general.querySelector('[data-incoming]');incoming.replaceChildren();for(const stale of privateView.querySelectorAll('[data-invite]'))if(!data.invites.some(i=>i.id===stale.dataset.invite))stale.remove();for(const invite of data.invites){const box=document.createElement('div'),label=document.createElement('strong'),id=document.createElement('small');box.dataset.invite=invite.id;label.textContent=invite.from+' is calling';id.textContent=invite.fromId;box.append(label,id);for(const action of ['Accept','Decline']){const b=document.createElement('button');b.textContent=action;b.className=action==='Accept'?'voice-join':'voice-decline';b.onclick=()=>{box.remove();if(action==='Accept')join(invite.room,null,invite.from);else request({action:'decline',room:invite.room}).catch(()=>{});};box.append(b);}incoming.append(box);if(!incomingSeen.has(invite.id)&&!call&&!busy){incomingSeen.add(invite.id);privateView.querySelector('h1').textContent=invite.from+' is calling';privateView.querySelector('[data-direct]').replaceChildren(box);showPrivate();}}if(!general.hidden)refreshLobby();}catch{}finally{checking=false;}},5000);
 window.addEventListener('pagehide',()=>{clearInterval(timer);leave();});paintMembers(general,{},'');controls();
}

